### ISSUE TITLE
Server claims to starts, but no active ports are opened.

### ISSUE THREAD

**Issue by forkrul** [AloisJanicek/org-roam-server-light#3]
Thanks, as I'm reaching 4k notes, I'm very happy to see your work on this project :)

1. The functionality triggers (from .el) and I see the function:
![image](https://user-images.githubusercontent.com/190788/104626148-d3e44380-5695-11eb-9e4a-60f9dd840fc6.png)
2. On running M-x org-roam-server-light I see
![image](https://user-images.githubusercontent.com/190788/104626248-f4140280-5695-11eb-9335-741a9b7a10b5.png)
3. No ports are however opened for the server. And no listeners are opened from python:
![image](https://user-images.githubusercontent.com/190788/104626381-2291dd80-5696-11eb-8d93-e59242437681.png)

Am I missing a step? 
How can I go about debugging the .el->.py calls?
 Is there any routing, setup that needs to be pre-configured for this to work?

**Comment by AloisJanicek** [comment]
There aren't really any .el -> py calls, information exchange between emacs and python server is done through writing and reading 6 different files in `org-roam-server-light-tmp-dir`. 

(I know... but it is simple and very lightweight, I didn't wanted to mess around with more advanced [IPC](https://en.wikipedia.org/wiki/Inter-process_communication).)

When the `org-roam-server-light-mode` is enabled, it sets one hook, creates `org-roam-server-light-tmp-dir`, writes initial values into those 6 files I mentioned above and then starts process:
```lisp
(let ((default-directory org-roam-server-light-dir))
          (start-process-shell-command "org-roam-server-light" "*org-roam-server-light-output-buffer*" "python main.py"))
```

which equals to:
```bash
cd ~/home/johndoe/where-i-cloned-org-roam-server-light/
python main.py
```
and that's it. 

If this step somehow fails, there should be some info it in `*org-roam-server-light-output-buffer*` buffer. You may be using the doom, so you need to type space and then Backspace in buffer switcher to be able to see special buffers there and switch into one of them.

This step would fail you for example if you didn't set the right value to `org-roam-server-light-dir` and emacs would be starting python server in the wrong directory. Double check this please. 
I should add there a proper check which would rise an error if that dir doesn't exists or if that dir doesn't contain "`main.py`" or something like that.

I think that there are no special python dependencies for this project, so that's most likely what is not failing you here.

![image](https://user-images.githubusercontent.com/804158/104639722-08f99180-56a8-11eb-868f-70bf3dbe8364.png)

**Comment by forkrul** [comment]
Thanks, the let line you supplied, actually triggers execution of the python script, so it's like you anticipated, that step fails.
`#+RESULTS:
: #<process org-roam-server-light>`

I'll look into it, and see why this doesn't trigger automatically, thanks for the explanation.
